<a href="https://colab.research.google.com/github/AMALJITH7/Machine-Learning/blob/Task-2/Height_Weight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import math

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/weight-height.csv')
df

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [ ]:
df['Male']=np.where(df['Gender']=='Male',1,0)
df['Female']=np.where(df['Gender']=='Female',1,0)
df.head()

Gender     Height      Weight  Male  Female
0   Male  73.847017  241.893563     1       0
1   Male  68.781904  162.310473     1       0
2   Male  74.110105  212.740856     1       0
3   Male  71.730978  220.042470     1       0
4   Male  69.881796  206.349801     1       0

In [ ]:
df.drop(['Gender'],axis=1,inplace=True)
df.head()

Height      Weight  Male  Female
0  73.847017  241.893563     1       0
1  68.781904  162.310473     1       0
2  74.110105  212.740856     1       0
3  71.730978  220.042470     1       0
4  69.881796  206.349801     1       0

In [ ]:
dependent_variable=df['Height']
dependent_variable.head()

0    73.847017
1    68.781904
2    74.110105
3    71.730978
4    69.881796
Name: Height, dtype: float64

In [ ]:
independent_variable=df[['Weight','Male','Female']]
independent_variable.head()

Weight  Male  Female
0  241.893563     1       0
1  162.310473     1       0
2  212.740856     1       0
3  220.042470     1       0
4  206.349801     1       0

In [ ]:
x=independent_variable.values
y=dependent_variable.values

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train[0:10]

array([[118.76451826,   0.        ,   1.        ],
       [156.77858596,   0.        ,   1.        ],
       [211.11480969,   1.        ,   0.        ],
       [127.61650595,   0.        ,   1.        ],
       [177.06777435,   1.        ,   0.        ],
       [211.34249682,   1.        ,   0.        ],
       [158.27423286,   0.        ,   1.        ],
       [224.69516246,   1.        ,   0.        ],
       [107.72353806,   0.        ,   1.        ],
       [145.89884237,   1.        ,   0.        ]])

In [ ]:
y_test[0:10]

array([64.72387669, 67.27217066, 74.52097209, 65.880014  , 64.84630137,
       58.67095297, 64.80221252, 63.45040176, 68.52223104, 70.54220142])

In [ ]:
Scalar=MinMaxScaler()
x_train=Scalar.fit_transform(x_train)
x_test=Scalar.transform(x_test)

In [ ]:
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [ ]:
regressor.intercept_

54.50431786560109

In [ ]:
regressor.coef_

array([25.17347022, -0.47483909,  0.47483909])

In [ ]:
y_pred=regressor.predict(x_test)
y_pred

array([63.97801621, 69.07096077, 72.64788738, ..., 65.73574039,
       66.95413365, 66.44526544])

In [ ]:
y_test

array([64.72387669, 67.27217066, 74.52097209, ..., 66.07110689,
       65.64153589, 64.21086615])

In [ ]:
MSE=mean_squared_error(y_test,y_pred)
MSE

1.999288147632486

In [ ]:
SQRTMSE=math.sqrt(MSE)
SQRTMSE

1.413961862156291

In [ ]:
R2=r2_score(y_test,y_pred)
R2

0.864642597342521

In [ ]:
print(f'Accuracy is {R2*100}')

Accuracy is 86.4642597342521
