<a href="https://colab.research.google.com/github/AMALJITH7/Machine-Learning/blob/Task1/state_startups.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To predict the profit made by a startup on the basis of expenses incurred and the state where they operate

In [ ]:
import numpy as np
import pandas as pd
from numpy import math

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data=pd.read_csv('/content/drive/MyDrive/50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
data['New York_state']=np.where(data['State']=='New York',1,0)
data['California_state']=np.where(data['State']=='California',1,0)
data['Florida_state']=np.where(data['State']=='Florida',1,0)

In [ ]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit  \
0  165349.20       136897.80        471784.10    New York  192261.83   
1  162597.70       151377.59        443898.53  California  191792.06   
2  153441.51       101145.55        407934.54     Florida  191050.39   
3  144372.41       118671.85        383199.62    New York  182901.99   
4  142107.34        91391.77        366168.42     Florida  166187.94   

   New York_state  California_state  Florida_state  
0               1                 0              0  
1               0                 1              0  
2               0                 0              1  
3               1                 0              0  
4               0                 0              1

In [ ]:
data.drop(['State'],axis=1,inplace=True)
data.head()#The axis parameter is set to 1 to indicate columns; 0 is used for rows.

R&D Spend  Administration  Marketing Spend     Profit  New York_state  \
0  165349.20       136897.80        471784.10  192261.83               1   
1  162597.70       151377.59        443898.53  191792.06               0   
2  153441.51       101145.55        407934.54  191050.39               0   
3  144372.41       118671.85        383199.62  182901.99               1   
4  142107.34        91391.77        366168.42  166187.94               0   

   California_state  Florida_state  
0                 0              0  
1                 1              0  
2                 0              1  
3                 0              0  
4                 0              1

In [ ]:
dependent_variable=data['Profit']
dependent_variable.head(5)

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [ ]:
independent_variable=data[['R&D Spend','Administration','Marketing Spend','New York_state','California_state','Florida_state']]
independent_variable.head(5)

R&D Spend  Administration  Marketing Spend  New York_state  \
0  165349.20       136897.80        471784.10               1   
1  162597.70       151377.59        443898.53               0   
2  153441.51       101145.55        407934.54               0   
3  144372.41       118671.85        383199.62               1   
4  142107.34        91391.77        366168.42               0   

   California_state  Florida_state  
0                 0              0  
1                 1              0  
2                 0              1  
3                 0              0  
4                 0              1

In [ ]:
y=dependent_variable.values
x=independent_variable.values

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train[0:10]

array([[5.5493950e+04, 1.0305749e+05, 2.1463481e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [4.6014020e+04, 8.5047440e+04, 2.0551764e+05, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [7.5328870e+04, 1.4413598e+05, 1.3405007e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [4.6426070e+04, 1.5769392e+05, 2.1079767e+05, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [9.1749160e+04, 1.1417579e+05, 2.9491957e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.1994324e+05, 1.5654742e+05, 2.5651292e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.0002300e+03, 1.2415304e+05, 1.9039300e+03, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [5.4205000e+02, 5.1743150e+04, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [6.5605480e+04, 1.5303206e+05,

In [ ]:
y_test[0:10]

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [ ]:
Scalar=MinMaxScaler()
x_train=Scalar.fit_transform(x_train)
x_test=Scalar.transform(x_test)

In [ ]:
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [ ]:
regressor.intercept_

44153.95466784852

In [ ]:
y_pred=regressor.predict(x_test)
y_pred

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230165,  67851.69209676,  98791.73374687,
       113969.43533012, 167921.0656955 ])

In [ ]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [ ]:
MSE=mean_squared_error(y_test,y_pred)
MSE

83502864.03257735

In [ ]:
SQRTMSE=math.sqrt(MSE)
SQRTMSE

9137.990152794944

In [ ]:
R2=r2_score(y_test,y_pred)
R2

0.9347068473282425

In [ ]:
print(f'Accuracy is {R2*100}')

Accuracy is 93.47068473282425
